
name: Build and Publish Docker Image

on:
  push:
    branches:
      - Feature/getWithSearch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and run with Docker Compose
        env:
          ENV: ${{ secrets.ENV }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          
        run: |
          docker-compose -f docker-compose.yml up -d --build

      - name: Install dependencies
        run: npm ci

      - name: Run Vitest tests
        run: npx vitest run __tests__

      - name: Push app image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/tech-challenge-fase-02:latest